/*
 * CrazyMainUI.java
 *
 * Created on __DATE__, __TIME__
 */

package ui;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.Random;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import bean.Guess;
import bean.State;

import dao.GuessDAO;
import dao.GuessDAOIMPL;
import dao.StateDAO;
import dao.StateDAOIMPL;

/**
 * 
 * @author __USER__
 */
public class CrazyMainUI extends javax.swing.JFrame {
	GuessDAO gdao = new GuessDAOIMPL();
	StateDAO sdao = new StateDAOIMPL();
	private State state;
	private Guess guess;
	private int[] whereImFrom = { -1, -1, -1, -1 };// 存储答案框中答案来源地的索引

	/** Creates new form CrazyMainUI */
	public CrazyMainUI() {
		initComponents();
		setLocationRelativeTo(null);
		myInit();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

		jLayeredPane1 = new javax.swing.JLayeredPane();
		jLabelShowword1 = new javax.swing.JLabel();
		jLabelShowwordbg1 = new javax.swing.JLabel();
		jLabelShowword2 = new javax.swing.JLabel();
		jLabelShowwordbg2 = new javax.swing.JLabel();
		jLabelShowword3 = new javax.swing.JLabel();
		jLabelShowwordbg3 = new javax.swing.JLabel();
		jLabelShowword4 = new javax.swing.JLabel();
		jLabelShowwordbg4 = new javax.swing.JLabel();
		jLabelSelectword1 = new javax.swing.JLabel();
		jLabelSelectbg1 = new javax.swing.JLabel();
		jLabelSelectword2 = new javax.swing.JLabel();
		jLabelSelectbg2 = new javax.swing.JLabel();
		jLabelSelectword3 = new javax.swing.JLabel();
		jLabelSelectbg3 = new javax.swing.JLabel();
		jLabelSelectword4 = new javax.swing.JLabel();
		jLabelSelectbg4 = new javax.swing.JLabel();
		jLabelSelectword5 = new javax.swing.JLabel();
		jLabelSelectbg5 = new javax.swing.JLabel();
		jLabelSelectword6 = new javax.swing.JLabel();
		jLabelSelectbg6 = new javax.swing.JLabel();
		jLabelSelectword7 = new javax.swing.JLabel();
		jLabelSelectbg7 = new javax.swing.JLabel();
		jLabelSelectword8 = new javax.swing.JLabel();
		jLabelSelectbg8 = new javax.swing.JLabel();
		jLabelSelectword9 = new javax.swing.JLabel();
		jLabelSelectbg9 = new javax.swing.JLabel();
		jLabelSelectword10 = new javax.swing.JLabel();
		jLabelSelectbg10 = new javax.swing.JLabel();
		jLabelSelectword11 = new javax.swing.JLabel();
		jLabelSelectbg11 = new javax.swing.JLabel();
		jLabelSelectword12 = new javax.swing.JLabel();
		jLabelSelectbg12 = new javax.swing.JLabel();
		jLabelSelectword13 = new javax.swing.JLabel();
		jLabelSelectbg13 = new javax.swing.JLabel();
		jLabelSelectword14 = new javax.swing.JLabel();
		jLabelSelectbg14 = new javax.swing.JLabel();
		jLabelSelectword15 = new javax.swing.JLabel();
		jLabelSelectbg15 = new javax.swing.JLabel();
		jLabelSelectword16 = new javax.swing.JLabel();
		jLabelSelectbg16 = new javax.swing.JLabel();
		jLabelSelectword17 = new javax.swing.JLabel();
		jLabelSelectbg17 = new javax.swing.JLabel();
		jLabelSelectword18 = new javax.swing.JLabel();
		jLabelSelectbg18 = new javax.swing.JLabel();
		jLabelSelectword19 = new javax.swing.JLabel();
		jLabelSelectbg19 = new javax.swing.JLabel();
		jLabelSelectword20 = new javax.swing.JLabel();
		jLabelSelectbg20 = new javax.swing.JLabel();
		jLabelSelectword21 = new javax.swing.JLabel();
		jLabelSelectbg21 = new javax.swing.JLabel();
		jLabelSelectword22 = new javax.swing.JLabel();
		jLabelSelectbg22 = new javax.swing.JLabel();
		jLabelSelectword23 = new javax.swing.JLabel();
		jLabelSelectbg23 = new javax.swing.JLabel();
		jLabelSelectword24 = new javax.swing.JLabel();
		jLabelSelectbg24 = new javax.swing.JLabel();
		jLabelShare = new javax.swing.JLabel();
		jLabelFree = new javax.swing.JLabel();
		jLabelAnswer = new javax.swing.JLabel();
		jLabelGuessImage = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		jLabelGold = new javax.swing.JLabel();
		jLabelLevel = new javax.swing.JLabel();
		jLabelPlus = new javax.swing.JLabel();
		jLabelBack = new javax.swing.JLabel();
		jLabelBackground = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings
				.createAutoBinding(
						org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE,
						jLabelBackground,
						org.jdesktop.beansbinding.ObjectProperty.create(),
						jLayeredPane1, org.jdesktop.beansbinding.BeanProperty
								.create("background"));
		bindingGroup.addBinding(binding);

		jLabelShowword1.setBounds(93, 293, 30, 30);
		jLayeredPane1.add(jLabelShowword1,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelShowwordbg1.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/ui/controls/word.png"))); // NOI18N
		jLabelShowwordbg1.setBounds(90, 290, 37, 39);
		jLayeredPane1.add(jLabelShowwordbg1,
				javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLabelShowword2.setBounds(153, 293, 30, 30);
		jLayeredPane1.add(jLabelShowword2,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelShowwordbg2.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/ui/controls/word.png"))); // NOI18N
		jLabelShowwordbg2.setBounds(150, 290, 37, 39);
		jLayeredPane1.add(jLabelShowwordbg2,
				javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLabelShowword3.setBounds(208, 293, 30, 30);
		jLayeredPane1.add(jLabelShowword3,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelShowwordbg3.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/ui/controls/word.png"))); // NOI18N
		jLabelShowwordbg3.setBounds(205, 290, 37, 39);
		jLayeredPane1.add(jLabelShowwordbg3,
				javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLabelShowword4.setBounds(263, 293, 30, 30);
		jLayeredPane1.add(jLabelShowword4,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelShowwordbg4.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/ui/controls/word.png"))); // NOI18N
		jLabelShowwordbg4.setBounds(260, 290, 37, 39);
		jLayeredPane1.add(jLabelShowwordbg4,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectword1.setFont(new java.awt.Font("幼圆", 0, 18));
		jLabelSelectword1.setBounds(33, 352, 30, 30);
		jLayeredPane1.add(jLabelSelectword1,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectbg1.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/ui/controls/word.png"))); // NOI18N
		jLabelSelectbg1.setBounds(30, 350, 35, 37);
		jLayeredPane1.add(jLabelSelectbg1,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectword2.setFont(new java.awt.Font("幼圆", 0, 18));
		jLabelSelectword2.setBounds(73, 352, 30, 30);
		jLayeredPane1.add(jLabelSelectword2,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectbg2.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/ui/controls/word.png"))); // NOI18N
		jLabelSelectbg2.setBounds(70, 350, 35, 37);
		jLayeredPane1.add(jLabelSelectbg2,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectword3.setFont(new java.awt.Font("幼圆", 0, 18));
		jLabelSelectword3.setBounds(113, 352, 30, 30);
		jLayeredPane1.add(jLabelSelectword3,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectbg3.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/ui/controls/word.png"))); // NOI18N
		jLabelSelectbg3.setBounds(110, 350, 35, 37);
		jLayeredPane1.add(jLabelSelectbg3,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectword4.setFont(new java.awt.Font("幼圆", 0, 18));
		jLabelSelectword4.setBounds(153, 352, 30, 30);
		jLayeredPane1.add(jLabelSelectword4,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectbg4.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/ui/controls/word.png"))); // NOI18N
		jLabelSelectbg4.setBounds(150, 350, 35, 37);
		jLayeredPane1.add(jLabelSelectbg4,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectword5.setFont(new java.awt.Font("幼圆", 0, 18));
		jLabelSelectword5.setBounds(193, 352, 30, 30);
		jLayeredPane1.add(jLabelSelectword5,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectbg5.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/ui/controls/word.png"))); // NOI18N
		jLabelSelectbg5.setBounds(190, 350, 35, 37);
		jLayeredPane1.add(jLabelSelectbg5,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectword6.setFont(new java.awt.Font("幼圆", 0, 18));
		jLabelSelectword6.setBounds(233, 352, 30, 30);
		jLayeredPane1.add(jLabelSelectword6,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectbg6.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/ui/controls/word.png"))); // NOI18N
		jLabelSelectbg6.setBounds(230, 350, 35, 37);
		jLayeredPane1.add(jLabelSelectbg6,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectword7.setFont(new java.awt.Font("幼圆", 0, 18));
		jLabelSelectword7.setBounds(273, 352, 30, 30);
		jLayeredPane1.add(jLabelSelectword7,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectbg7.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/ui/controls/word.png"))); // NOI18N
		jLabelSelectbg7.setBounds(270, 350, 35, 37);
		jLayeredPane1.add(jLabelSelectbg7,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectword8.setFont(new java.awt.Font("幼圆", 0, 18));
		jLabelSelectword8.setBounds(313, 352, 30, 30);
		jLayeredPane1.add(jLabelSelectword8,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectbg8.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/ui/controls/word.png"))); // NOI18N
		jLabelSelectbg8.setBounds(310, 350, 35, 37);
		jLayeredPane1.add(jLabelSelectbg8,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectword9.setFont(new java.awt.Font("幼圆", 0, 18));
		jLabelSelectword9.setBounds(33, 402, 30, 30);
		jLayeredPane1.add(jLabelSelectword9,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectbg9.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/ui/controls/word.png"))); // NOI18N
		jLabelSelectbg9.setBounds(30, 400, 35, 37);
		jLayeredPane1.add(jLabelSelectbg9,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectword10.setFont(new java.awt.Font("幼圆", 0, 18));
		jLabelSelectword10.setBounds(73, 402, 30, 30);
		jLayeredPane1.add(jLabelSelectword10,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectbg10.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/ui/controls/word.png"))); // NOI18N
		jLabelSelectbg10.setBounds(70, 400, 35, 37);
		jLayeredPane1.add(jLabelSelectbg10,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectword11.setFont(new java.awt.Font("幼圆", 0, 18));
		jLabelSelectword11.setBounds(113, 402, 30, 30);
		jLayeredPane1.add(jLabelSelectword11,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectbg11.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/ui/controls/word.png"))); // NOI18N
		jLabelSelectbg11.setBounds(110, 400, 35, 37);
		jLayeredPane1.add(jLabelSelectbg11,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectword12.setFont(new java.awt.Font("幼圆", 0, 18));
		jLabelSelectword12.setBounds(153, 402, 30, 30);
		jLayeredPane1.add(jLabelSelectword12,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectbg12.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/ui/controls/word.png"))); // NOI18N
		jLabelSelectbg12.setBounds(150, 400, 35, 37);
		jLayeredPane1.add(jLabelSelectbg12,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectword13.setFont(new java.awt.Font("幼圆", 0, 18));
		jLabelSelectword13.setBounds(193, 402, 30, 30);
		jLayeredPane1.add(jLabelSelectword13,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectbg13.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/ui/controls/word.png"))); // NOI18N
		jLabelSelectbg13.setBounds(190, 400, 35, 37);
		jLayeredPane1.add(jLabelSelectbg13,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectword14.setFont(new java.awt.Font("幼圆", 0, 18));
		jLabelSelectword14.setBounds(233, 403, 30, 30);
		jLayeredPane1.add(jLabelSelectword14,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectbg14.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/ui/controls/word.png"))); // NOI18N
		jLabelSelectbg14.setBounds(230, 400, 35, 37);
		jLayeredPane1.add(jLabelSelectbg14,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectword15.setFont(new java.awt.Font("幼圆", 0, 18));
		jLabelSelectword15.setBounds(273, 403, 30, 30);
		jLayeredPane1.add(jLabelSelectword15,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectbg15.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/ui/controls/word.png"))); // NOI18N
		jLabelSelectbg15.setBounds(270, 400, 35, 37);
		jLayeredPane1.add(jLabelSelectbg15,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectword16.setFont(new java.awt.Font("幼圆", 0, 18));
		jLabelSelectword16.setBounds(313, 403, 30, 30);
		jLayeredPane1.add(jLabelSelectword16,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectbg16.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/ui/controls/word.png"))); // NOI18N
		jLabelSelectbg16.setBounds(310, 400, 35, 37);
		jLayeredPane1.add(jLabelSelectbg16,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectword17.setFont(new java.awt.Font("幼圆", 0, 18));
		jLabelSelectword17.setBounds(33, 453, 30, 30);
		jLayeredPane1.add(jLabelSelectword17,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectbg17.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/ui/controls/word.png"))); // NOI18N
		jLabelSelectbg17.setBounds(30, 450, 35, 37);
		jLayeredPane1.add(jLabelSelectbg17,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectword18.setFont(new java.awt.Font("幼圆", 0, 18));
		jLabelSelectword18.setBounds(73, 453, 30, 30);
		jLayeredPane1.add(jLabelSelectword18,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectbg18.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/ui/controls/word.png"))); // NOI18N
		jLabelSelectbg18.setBounds(70, 450, 35, 37);
		jLayeredPane1.add(jLabelSelectbg18,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectword19.setFont(new java.awt.Font("幼圆", 0, 18));
		jLabelSelectword19.setBounds(113, 453, 30, 30);
		jLayeredPane1.add(jLabelSelectword19,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectbg19.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/ui/controls/word.png"))); // NOI18N
		jLabelSelectbg19.setBounds(110, 450, 35, 37);
		jLayeredPane1.add(jLabelSelectbg19,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectword20.setFont(new java.awt.Font("幼圆", 0, 18));
		jLabelSelectword20.setBounds(153, 453, 30, 30);
		jLayeredPane1.add(jLabelSelectword20,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectbg20.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/ui/controls/word.png"))); // NOI18N
		jLabelSelectbg20.setBounds(150, 450, 35, 37);
		jLayeredPane1.add(jLabelSelectbg20,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectword21.setFont(new java.awt.Font("幼圆", 0, 18));
		jLabelSelectword21.setBounds(193, 453, 30, 30);
		jLayeredPane1.add(jLabelSelectword21,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectbg21.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/ui/controls/word.png"))); // NOI18N
		jLabelSelectbg21.setBounds(190, 450, 35, 37);
		jLayeredPane1.add(jLabelSelectbg21,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectword22.setFont(new java.awt.Font("幼圆", 0, 18));
		jLabelSelectword22.setBounds(233, 453, 30, 30);
		jLayeredPane1.add(jLabelSelectword22,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectbg22.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/ui/controls/word.png"))); // NOI18N
		jLabelSelectbg22.setBounds(230, 450, 35, 37);
		jLayeredPane1.add(jLabelSelectbg22,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectword23.setFont(new java.awt.Font("幼圆", 0, 18));
		jLabelSelectword23.setBounds(273, 453, 30, 30);
		jLayeredPane1.add(jLabelSelectword23,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectbg23.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/ui/controls/word.png"))); // NOI18N
		jLabelSelectbg23.setBounds(270, 450, 35, 37);
		jLayeredPane1.add(jLabelSelectbg23,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectword24.setFont(new java.awt.Font("幼圆", 0, 18));
		jLabelSelectword24.setBounds(313, 453, 30, 30);
		jLayeredPane1.add(jLabelSelectword24,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelSelectbg24.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/ui/controls/word.png"))); // NOI18N
		jLabelSelectbg24.setBounds(310, 450, 35, 37);
		jLayeredPane1.add(jLabelSelectbg24,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelShare.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/ui/controls/btn_share.png"))); // NOI18N
		jLabelShare.setBounds(300, 150, 60, 63);
		jLayeredPane1.add(jLabelShare, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelFree.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/ui/controls/free_gold.png"))); // NOI18N
		jLabelFree.setBounds(20, 210, 59, 63);
		jLayeredPane1.add(jLabelFree, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelAnswer.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/ui/controls/btn_showword.png"))); // NOI18N
		jLabelAnswer.setBounds(20, 120, 60, 63);
		jLayeredPane1.add(jLabelAnswer, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelGuessImage
				.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelGuessImage
				.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jLabelGuessImage.setBounds(107, 110, 170, 170);
		jLayeredPane1.add(jLabelGuessImage,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 170,
				Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 170,
				Short.MAX_VALUE));

		jPanel1.setBounds(107, 110, 170, 170);
		jLayeredPane1.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelGold.setFont(new java.awt.Font("幼圆", 0, 12));
		jLabelGold.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelGold.setBounds(335, 20, 35, 18);
		jLayeredPane1.add(jLabelGold, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelLevel.setFont(new java.awt.Font("幼圆", 0, 18));
		jLabelLevel.setForeground(new java.awt.Color(255, 255, 255));
		jLabelLevel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabelLevel.setText("111");
		jLabelLevel
				.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		jLabelLevel.setBounds(170, 17, 40, 20);
		jLayeredPane1.add(jLabelLevel, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelPlus.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/ui/controls/btn_gold.png"))); // NOI18N
		jLabelPlus.setBounds(280, 10, 100, 40);
		jLayeredPane1.add(jLabelPlus, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelBack.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/ui/controls/btn_back.png"))); // NOI18N
		jLabelBack.setBounds(10, 10, 60, 40);
		jLayeredPane1.add(jLabelBack, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/ui/controls/background.png"))); // NOI18N
		jLabelBackground.setBounds(0, 0, 384, 512);
		jLayeredPane1.add(jLabelBackground,
				javax.swing.JLayeredPane.DEFAULT_LAYER);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)
						.addComponent(jLayeredPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 384,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(81, 81, 81)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 512,
				javax.swing.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>
		// GEN-END:initComponents

	private void myInit() {
		getCommonEvents();
		addEventWordbg();
		// 获取文字库
		GetGuessWords();
		// 关卡初始化，金币初始化，文字初始化level改变的时候就会初始化
		changeLevel();
	}

	private JLabel[] selectWord = new JLabel[24];
	private JLabel[] selectWordbg = new JLabel[24];
	private JLabel[] answerWord = new JLabel[4];
	private JLabel[] answerWordbg = new JLabel[4];
	// 用于标志对应索引是否已被提醒
	private int isshow[] = { 0, 0, 0, 0 };

	// 关卡初始化，金币初始化，文字初始化level改变的时候就会初始化
	private void changeLevel() {
		isshow=new int[]{0,0,0,0};
		state = sdao.GetState();
		if (state.getLevel() > 50) {
			JOptionPane.showMessageDialog(CrazyMainUI.this, "恭喜您，通关了！");
			state.setLevel(1);
			sdao.UpdateState(state);
		}
		guess = gdao.GetOneGuessByLevel(state.getLevel());
		jLabelLevel.setText(String.valueOf(state.getLevel()));
		jLabelGold.setText(String.valueOf(state.getGold()));
		ImageIcon icon = new ImageIcon(getClass().getResource(
				"guessimage/" + guess.getImgName()));
		// 设置图片的长，宽，高
		icon.setImage(icon.getImage().getScaledInstance(
				jLabelGuessImage.getWidth(), jLabelGuessImage.getHeight(), 1));
		jLabelGuessImage.setIcon(icon);
		// 设置文字
		setWordText();
	}

	// 获取文字库
	private ArrayList<String> GuessWords;

	private void GetGuessWords() {
		GuessWords = new ArrayList<String>();
		ArrayList<Guess> guessList = gdao.getAllGuess();
		for (Guess guess : guessList) {
			String answer = guess.getAnswer();
			for (int i = 0; i < 4; i++) {
				String word = String.valueOf(answer.charAt(i));
				if (!GuessWords.contains(word)) {
					GuessWords.add(word);
				}
			}
		}
	}

	private ArrayList<String> wordList;

	private void setWordText() {
		for (int i = 0; i < answerWord.length; i++) {
			answerWord[i].setText("");
		}
		// 重置存储答案索引的数组
		whereImFrom = new int[] { -1, -1, -1, -1 };
		// 将待选文字框设置为可见
		for (int i = 0; i < selectWordbg.length; i++) {
			selectWordbg[i].setVisible(true);
			selectWord[i].setVisible(true);
		}
		wordList = new ArrayList<String>();
		for (int i = 0; i < 4; i++) {
			wordList.add(String.valueOf(guess.getAnswer().charAt(i)));
		}
		Random random = new Random();
		for (int i = 0; i < 20; i++) {
			int index = random.nextInt(GuessWords.size());
			String word = GuessWords.get(index);
			if (!wordList.contains(word)) {
				wordList.add(word);
			} else {
				i--;
			}
		}
		for (int i = 0; i < selectWord.length; i++) {
			int index = random.nextInt(wordList.size());
			selectWord[i].setText(wordList.remove(index));
		}
	}

	private void addEventWordbg() {
		for (int i = 0; i < selectWord.length; i++) {
			selectWord[i] = getJLabel("jLabelSelectword", i + 1);
			selectWordbg[i] = getJLabel("jLabelSelectbg", i + 1);
		}
		for (int i = 0; i < answerWord.length; i++) {
			answerWord[i] = getJLabel("jLabelShowword", i + 1);
			answerWordbg[i] = getJLabel("jLabelShowwordbg", i + 1);
		}
		for (int i = 0; i < selectWordbg.length; i++) {
			addSelectWordEvents(i);
		}
		for (int i = 0; i < answerWordbg.length; i++) {
			answerSelectWordEvents(i);
		}
	}

	private JLabel getJLabel(String name, int i) {
		JLabel jLabel = null;
		try {
			Field field = this.getClass().getDeclaredField(name + i);
			jLabel = (JLabel) field.get(this);
		} catch (Exception e) {

			e.printStackTrace();
		}
		return jLabel;
	}

	private void getCommonEvents() {

		changeImage(jLabelBack, "btn_back_press.png", "btn_back.png");
		changeImage(jLabelPlus, "btn_gold_press.png", "btn_gold.png");
		changeImage(jLabelShare, "btn_share_press.png", "btn_share.png");
		changeImage(jLabelAnswer, "btn_showword_press.png", "btn_showword.png");
		changeImage(jLabelFree, "free_gold_press.png", "free_gold.png");
		jLabelBack.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent e) {

				new CrazyLoadingUI().setVisible(true);
				CrazyMainUI.this.dispose();
			}

		});
		jLabelAnswer.addMouseListener(new MouseAdapter() {

			@Override
			public void mouseClicked(MouseEvent e) {
				
		
				if (JOptionPane.showConfirmDialog(CrazyMainUI.this,
						"你确定要用50金币换取一个正确字吗？") == 0) {
					if (state.getGold() < 50) {
						JOptionPane.showMessageDialog(CrazyMainUI.this,
								"你没钱了，别点了，傻吊！");
						return;
					}
					state.setGold(state.getGold() - 50);
					sdao.UpdateState(state);
					jLabelGold.setText(String.valueOf(state.getGold()));
					// 获取当前局的答案
					String answer = guess.getAnswer();
					// 随机提醒，不重复提醒-int []isshow={0,0,0,0}
					// 获取一个索引index(0,3)用于获取答案字符
					Random random = new Random();
					int index = -1;
					while (true) {
						int count=0;
						index = random.nextInt(answer.length());
						if (isshow[index] == 0) {
							break;
						}
						
						for (int i : isshow) {
							count += i;
						}
						if (count == 4) {
							JOptionPane.showMessageDialog(CrazyMainUI.this,
									"本轮提示已经用完");
							return;
						}
					}
					String word = answer.charAt(index) + "";
					// 将该索引存入isshow，并提示该字符
					isshow[index] = 1;
					JOptionPane.showMessageDialog(CrazyMainUI.this, "有个字为"
							+ word);
					// 将获取的word放置在答案框相应位置
					putWordToAnswer(index, word);

				} else {
					return;
				}
			}

		});

	}

	private void putWordToAnswer(int index, String word) {
		int SelectIndex = -1;
		for (int i = 0; i < selectWord.length; i++) {
			if (word.equals(selectWord[i].getText())) {
				SelectIndex = i;
				break;
			}
		}
		Checkisexistsin(index);
		whereImFrom[index] = SelectIndex;
		Checkisexistsin(word);
		selectWord[SelectIndex].setVisible(false);
		selectWordbg[SelectIndex].setVisible(false);
		answerWord[index].setText(word);
		if (isanswerYes()) {
			JOptionPane.showMessageDialog(CrazyMainUI.this, "恭喜你,答对了！");
			state.setLevel(state.getLevel() + 1);
			state.setGold(state.getGold() + 100);
			sdao.UpdateState(state);
			changeLevel();
		}
	}
	private void Checkisexistsin(int index){
		if(whereImFrom[index]!=-1){//有来源，即有文字，就要还回去
			selectWord[whereImFrom[index]].setVisible(true);
			selectWordbg[whereImFrom[index]].setVisible(true);
			whereImFrom[index]=-1;
			answerWord[index].setText("");
		}
	}
	private void Checkisexistsin(String word){
		for(int i=0;i<answerWord.length;i++){
			if(word.equals(answerWord[i].getText())){
				answerWord[i].setText("");
				selectWord[whereImFrom[i]].setVisible(true);
				selectWordbg[whereImFrom[i]].setVisible(true);
				whereImFrom[i]=-1;
			}
		}
	}

	private void changeImage(final JLabel jlabel, final String fileName1,
			final String fileName2) {
		jlabel.addMouseListener(new MouseAdapter() {

			@Override
			public void mouseClicked(MouseEvent e) {

			}

			@Override
			public void mousePressed(MouseEvent e) {
				ImageIcon icon = new ImageIcon(getClass().getResource(
						"controls/" + fileName1));
				jlabel.setIcon(icon);
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				ImageIcon icon = new ImageIcon(getClass().getResource(
						"controls/" + fileName2));
				jlabel.setIcon(icon);
			}

		});
	}

	private void addSelectWordEvents(final int i) {// 重载待选文字添加事件方法
		changeImage(selectWordbg[i], "word_press.png", "word.png");
		selectWordbg[i].addMouseListener(new MouseAdapter() {
			

			@Override
			public void mouseClicked(MouseEvent e) {
				// TODO Auto-generated method stub
				// 判断能否放置
				int index = isAnswerEmpty();
				// 判断放置位置，放置在前面
				if (index == -1) {
					return;
				}
				// 放置的文字是什么？从哪里getText()?
				whereImFrom[index] = i;
				answerWord[index].setText(selectWord[i].getText());// 从selectWord[i]中获取Text赋值给answerWord[i]中
				// 原本被点击的文字以及背景要被隐藏
				selectWord[i].setVisible(false);
				selectWordbg[i].setVisible(false);
				// 判断放置文字后是否满员，如何判断,如果满员，判断是否正确
				if (isanswerYes()) {
					JOptionPane.showMessageDialog(CrazyMainUI.this, "恭喜你答对了");
					state.setLevel(state.getLevel() + 1);
					state.setGold(state.getGold() + 10);
					sdao.UpdateState(state);
					changeLevel();
				}
			}

		});
	}

	private boolean isanswerYes() {
		if (isAnswerEmpty() == -1) {
			String answer = "";
			for (JLabel jlabel : answerWord) {
				answer += jlabel.getText();
			}
			if (answer.equals(guess.getAnswer())) {
				return true;
			}
		}
		return false;
	}

	private void answerSelectWordEvents(final int i) {
		changeImage(answerWordbg[i], "word_press.png", "word.png");
		answerWordbg[i].addMouseListener(new MouseAdapter() {

			@Override
			public void mouseClicked(MouseEvent e) {
				// TODO Auto-generated method stub
				// 判断从whereImFrom返回来的selectWord的索引
				int index = whereImFrom[i];
				if (index == -1) {
					return;
				}

				answerWord[i].setText("");
				whereImFrom[i] = -1;

				selectWord[index].setVisible(true);
				selectWordbg[index].setVisible(true);
			}

		});
	}

	private int isAnswerEmpty() {
		for (int i = 0; i < answerWord.length; i++) {
			if ("".equals(answerWord[i].getText())) {
				return i;
			}
		}
		return -1;
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new CrazyMainUI().setVisible(true);
			}
		});
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabelAnswer;
	private javax.swing.JLabel jLabelBack;
	private javax.swing.JLabel jLabelBackground;
	private javax.swing.JLabel jLabelFree;
	private javax.swing.JLabel jLabelGold;
	private javax.swing.JLabel jLabelGuessImage;
	private javax.swing.JLabel jLabelLevel;
	private javax.swing.JLabel jLabelPlus;
	private javax.swing.JLabel jLabelSelectbg1;
	private javax.swing.JLabel jLabelSelectbg10;
	private javax.swing.JLabel jLabelSelectbg11;
	private javax.swing.JLabel jLabelSelectbg12;
	private javax.swing.JLabel jLabelSelectbg13;
	private javax.swing.JLabel jLabelSelectbg14;
	private javax.swing.JLabel jLabelSelectbg15;
	private javax.swing.JLabel jLabelSelectbg16;
	private javax.swing.JLabel jLabelSelectbg17;
	private javax.swing.JLabel jLabelSelectbg18;
	private javax.swing.JLabel jLabelSelectbg19;
	private javax.swing.JLabel jLabelSelectbg2;
	private javax.swing.JLabel jLabelSelectbg20;
	private javax.swing.JLabel jLabelSelectbg21;
	private javax.swing.JLabel jLabelSelectbg22;
	private javax.swing.JLabel jLabelSelectbg23;
	private javax.swing.JLabel jLabelSelectbg24;
	private javax.swing.JLabel jLabelSelectbg3;
	private javax.swing.JLabel jLabelSelectbg4;
	private javax.swing.JLabel jLabelSelectbg5;
	private javax.swing.JLabel jLabelSelectbg6;
	private javax.swing.JLabel jLabelSelectbg7;
	private javax.swing.JLabel jLabelSelectbg8;
	private javax.swing.JLabel jLabelSelectbg9;
	private javax.swing.JLabel jLabelSelectword1;
	private javax.swing.JLabel jLabelSelectword10;
	private javax.swing.JLabel jLabelSelectword11;
	private javax.swing.JLabel jLabelSelectword12;
	private javax.swing.JLabel jLabelSelectword13;
	private javax.swing.JLabel jLabelSelectword14;
	private javax.swing.JLabel jLabelSelectword15;
	private javax.swing.JLabel jLabelSelectword16;
	private javax.swing.JLabel jLabelSelectword17;
	private javax.swing.JLabel jLabelSelectword18;
	private javax.swing.JLabel jLabelSelectword19;
	private javax.swing.JLabel jLabelSelectword2;
	private javax.swing.JLabel jLabelSelectword20;
	private javax.swing.JLabel jLabelSelectword21;
	private javax.swing.JLabel jLabelSelectword22;
	private javax.swing.JLabel jLabelSelectword23;
	private javax.swing.JLabel jLabelSelectword24;
	private javax.swing.JLabel jLabelSelectword3;
	private javax.swing.JLabel jLabelSelectword4;
	private javax.swing.JLabel jLabelSelectword5;
	private javax.swing.JLabel jLabelSelectword6;
	private javax.swing.JLabel jLabelSelectword7;
	private javax.swing.JLabel jLabelSelectword8;
	private javax.swing.JLabel jLabelSelectword9;
	private javax.swing.JLabel jLabelShare;
	private javax.swing.JLabel jLabelShowword1;
	private javax.swing.JLabel jLabelShowword2;
	private javax.swing.JLabel jLabelShowword3;
	private javax.swing.JLabel jLabelShowword4;
	private javax.swing.JLabel jLabelShowwordbg1;
	private javax.swing.JLabel jLabelShowwordbg2;
	private javax.swing.JLabel jLabelShowwordbg3;
	private javax.swing.JLabel jLabelShowwordbg4;
	private javax.swing.JLayeredPane jLayeredPane1;
	private javax.swing.JPanel jPanel1;
	private org.jdesktop.beansbinding.BindingGroup bindingGroup;
	// End of variables declaration//GEN-END:variables

}