/*
 * CrazyLoadingUI.java
 *
 * Created on __DATE__, __TIME__
 */

package ui;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 * 
 * @author __USER__
 */
public class CrazyLoadingUI extends javax.swing.JFrame {

	/** Creates new form CrazyLoadingUI */
	public CrazyLoadingUI() {
		try {
			UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
		} catch (Exception e) {
			e.printStackTrace();
		}
		initComponents();
		setLocationRelativeTo(null);
		new Thread(){
			public void run(){	
				try {
					Thread.sleep(2000);
					CrazyLoadingUI.this.dispose();
					Thread.sleep(500);
					java.awt.EventQueue.invokeLater(new Runnable() {
						public void run() {
							new CrazyStartUI().setVisible(true);
						}
					});
				} catch (InterruptedException e) {	
					e.printStackTrace();
				}
			}
		}.start();
	}
	public CrazyLoadingUI(int i){
		initComponents();
		setLocationRelativeTo(null);
		new Thread(){
			public void run(){	
				try {
					Thread.sleep(2000);
					CrazyLoadingUI.this.dispose();
					Thread.sleep(500);
					java.awt.EventQueue.invokeLater(new Runnable() {
						public void run() {
							new CrazyMainUI().setVisible(true);
						}
					});
				} catch (InterruptedException e) {	
					e.printStackTrace();
				}
			}
		}.start();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setUndecorated(true);

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/ui/controls/loading_logo.png"))); // NOI18N

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 384,
				javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 512,
				javax.swing.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>
		// GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new CrazyLoadingUI().setVisible(true);
			}
		});
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	// End of variables declaration//GEN-END:variables

}